---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: backend-secrets
  namespace: appgues
  labels:
    app: backend
    component: secrets
stringData:
  FLASK_DB_PASSWORD: "secretpass"
  FLASK_DB_USER: "postgres"
