---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: appgues
  labels: &labels
    app: backend
    component: deployment
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: backend
        image: alissonrm/faculdade:backend
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-configmap
        - secretRef:
            name: backend-secrets
        resources:
          limits:
            cpu: "1.0"
            memory: "1024Mi"
          requests:
            cpu: "0.5"
            memory: "512Mi"
