---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: appgues 
  labels:
    app: backend
    component: configmap
data:
  FLASK_APP: "run.py"
  FLASK_DB_TYPE: "postgres"
  FLASK_DB_NAME: "postgres"
  FLASK_DB_HOST: "postgres-service"
  FLASK_DB_PORT: "5432"
