---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: appgues
  labels:
    app: backend
    component: service
spec:
  type: ClusterIP
  selector:
    app: backend
    component: deployment
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
