---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: appgues
  labels:
    app: frontend
    component: service
spec:
  type: NodePort
  selector:
    app: frontend
    component: deployment
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30001
