---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: appgues
  labels: &labels
    app: frontend
    component: deployment
spec:
  replicas: 1
  selector:
    matchLabels: *labels
  template:
    metadata:
      labels: *labels
    spec:
      containers:
      - name: frontend
        image: alissonrm/faculdade:frontend
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        envFrom:
        - configMapRef:
            name: frontend-configmap
