---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres-secrets
  namespace: appgues
  labels:
    app: postgres
    component: secrets
stringData:
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "secretpass"
  POSTGRES_PASSWORD: "secretpass"
  POSTGRES_HOST_AUTH_METHOD: "md5"  
